markets_by_district={
  "Jhunjhunu": [
  "Gudhagorji",
  "Jhunjhunu",
  "Nawalgarh",
  "Surajgarh",
 ],
"Adilabad": [
  "Adilabad",
  "Adilabad(Rythu Bazar)",
  "Asifabad",
  "Bhainsa",
  "Chinnoar",
  "Ichoda",
  "Kagaznagar",
  "Khanapur",
  "Laxettipet",
 ],
"Agar Malwa": [
  "Soyatkalan(F&V)",
 ],
"Agra": [
  "Achnera",
  "Agra",
  "Fatehabad",
  "Fatehpur Sikri",
  "Jagnair",
  "Khairagarh",
  "Samsabad",
 ],
"Ahmedabad": [
  "Ahmedabad",
  "Ahmedabad(Chimanbhai Patal Market Vasana)",
  "Bavla",
  "Dhandhuka",
  "Mandal",
  "Sanad",
  "Viramgam",
 ],
"Ahmednagar": [
  "Ahmednagar",
  "Akole",
  "Jamkhed",
  "Karjat",
  "Kopargaon",
  "Om Chaitanya Multistate Agro Purpose CoOp Society ",
  "Rahata",
  "Rahuri",
  "Rahuri(Songaon)",
  "Rahuri(Vambori)",
  "Sangamner",
  "Shevgaon",
  "Shevgaon(Bodhegaon)",
  "Shrigonda",
  "Shrirampur",
 ],
"Ajmer": [
  "Ajmer(F&V)",
  "Beawar",
  "Kekri",
  "Madanganj Kishangarh",
  "Vijaynagar",
 ],
"Akola": [
  "Akola",
  "Murtizapur",
 ],
"Alappuzha": [
  "Alappuzha",
  "Aroor",
  "Chengannur",
  "Cherthala",
  "Harippad",
  "Kayamkulam",
  "Madhavapuram",
  "Mannar",
 ],
"Aligarh": [
  "Aligarh",
  "Atrauli",
  "Charra",
  "Khair",
 ],
"Alipurduar": [
  "Alipurduar",
  "Falakata",
 ],
"Alirajpur": [
  "Alirajpur",
  "Jobat",
 ],
"Alwar": [
  "Alwar",
  "Alwar (F&V)",
  "Bahror",
  "Bansoor",
  "Barodamev",
  "Khairthal",
  "Kherli",
  "Laxmangarh (Barodamev)",
 ],
"Amarawati": [
  "Achalpur",
  "Amarawati",
  "Amrawati(Frui & Veg. Market)",
  "Anajngaon",
  "Daryapur",
  "Morshi",
  "Shetkari Khushi Bazar",
  "Varud(Rajura Bazar)",
 ],
"Ambala": [
  "Ambala Cantt.",
  "Ambala City(Subji Mandi)",
  "Barara",
  "Mullana",
  "Naraingarh",
  "Shahzadpur",
 ],
"Ambedkarnagar": [
  "Akbarpur",
 ],
"Amethi": [
  "Jafarganj",
  "Sultanpur",
 ],
"Amreli": [
  "Amreli",
  "Babra",
  "Bagasara",
  "Damnagar",
  "Dhari",
  "Khambha",
  "Rajula",
  "Savarkundla",
 ],
"Amritsar": [
  "Ajnala",
  "Amritsar",
  "Amritsar(Amritsar Mewa Mandi)",
  "Attari",
  "Majitha",
  "Mehta",
  "Rayya",
  "Rayya(Sathiala)",
 ],
"Amroha": [
  "Amroha",
  "Dhanaura",
  "Hasanpur",
 ],
"Anand": [
  "Anand(Veg,Yard,Anand)",
  "Borsad",
  "Khambhat(Grain Market)",
  "Khambhat(Veg Yard Khambhat)",
  "Umreth",
 ],
"Anantnag": [
  "Ashahipora (Anantnagh)",
  "Kulgam",
 ],
"Anupgarh": [
  "Gharsana",
  "Raisingh Nagar",
  "Sri Vijayanagar",
 ],
"Anupur": [
  "Anuppur",
 ],
"Ariyalur": [
  "Andimadom",
  "Ariyalur(Uzhavar Sandhai)",
  "Jeyankondam (Uzhavar Sandhai )",
 ],
"Ashoknagar": [
  "Ashoknagar",
  "Chanderi",
  "Isagarh",
  "Mungawali",
  "Piprai",
  "Shadora",
 ],
"Auraiya": [
  "Achalda",
  "Auraiya",
  "Dibiapur",
 ],
"Ayodhya": [
  "Faizabad",
  "Rudauli",
 ],
"Azamgarh": [
  "Azamgarh",
 ],
"Badaun": [
  "Babrala",
  "Badayoun",
  "Bilsi",
  "Dataganj",
  "Shahaswan",
  "Ujhani",
  "Visoli",
  "Wazirganj",
 ],
"Badwani": [
  "Anjad",
  "Badwani",
  "Badwani(F&V)",
  "Khetia",
  "Sendhwa",
  "Sendhwa(F&V)",
 ],
"Bagalkot": [
  "Bagalakot",
 ],
"Baghpat": [
  "Bagpat",
  "Baraut",
  "Khekda",
 ],
"Bahraich": [
  "Bahraich",
  "Naanpara",
 ],
"Balaghat": [
  "Lalbarra",
  "Mohgaon",
 ],
"Balasore": [
  "Jaleswar",
  "Nilagiri",
 ],
"Ballia": [
  "Ballia",
  "Chitwadagaon",
  "Rasda",
  "Vilthararoad",
 ],
"Balod": [
  "Balod",
  "Dondi",
 ],
"Balodabazar": [
  "Balodabazar",
  "Bhatapara",
  "Bhatgaon",
  "Sarsiwan",
 ],
"Balotra": [
  "Balotra",
 ],
"Balrampur": [
  "Balrampur",
  "Panchpedwa",
  "Ramanujganj",
  "Tulsipur",
 ],
"Banaskanth": [
  "Amirgadh",
  "Bhabhar",
  "Deesa",
  "Deesa(Bhildi)",
  "Deesa(Deesa Veg Yard)",
  "Dhanera",
  "Palanpur",
  "Panthawada",
  "Thara",
  "Thara(Shihori)",
  "Tharad",
  "Vadgam",
  "Vav",
 ],
"Banda": [
  "Atarra",
  "Baberu",
  "Banda",
 ],
"Bangalore": [
  "Bangalore",
  "Binny Mill (F&V), Bangalore",
  "Doddaballa Pur",
  "Hoskote",
  "Ramanagara",
 ],
"Banka": [
  "Barahat",
 ],
"Bankura": [
  "Bankura Sadar",
  "Bishnupur(Bankura)",
  "Indus(Bankura Sadar)",
  "Khatra",
 ],
"Barabanki": [
  "Barabanki",
  "Safdarganj",
 ],
"Baran": [
  "Anta",
  "Atru",
  "Baran",
  "Chhabra",
  "Chhipabarod (Chhabra)",
  "Kawai Salpura (Atru)",
  "Nahargarh",
  "Samraniyan",
 ],
"Bareilly": [
  "Anwala",
  "Bahedi",
  "Bareilly",
  "Richha",
 ],
"Bargarh": [
  "Bargarh",
  "Bargarh(Barapalli)",
  "Sohela",
 ],
"Barmer": [
  "Barmer",
 ],
"Barnala": [
  "Barnala",
 ],
"Barpeta": [
  "Barpeta Road",
 ],
"Bastar": [
  "Jagdalpur",
 ],
"Basti": [
  "Basti",
 ],
"Beawar": [
  "Vijaynagar",
 ],
"Beed": [
  "Ambejaogai",
  "Beed",
  "Gevrai",
  "Kille Dharur",
  "Majalgaon",
 ],
"Belgaum": [
  "Belgaum",
 ],
"Bellary": [
  "Bellary",
  "Kottur",
 ],
"Bemetara": [
  "Dadhi",
 ],
"Betul": [
  "Betul",
 ],
"Bhadohi(Sant Ravi Nagar)": [
  "Gopiganj",
 ],
"Bhadrak": [
  "Bhadrak",
 ],
"Bhandara": [
  "Bhandara",
  "Tumsar",
 ],
"Bharatpur": [
  "Bayana",
  "Bharatpur",
  "Deeg",
  "Kama",
  "Kumher",
  "Nadwai",
  "Pahari",
 ],
"Bharuch": [
  "Ankleshwar",
  "Bharuch",
  "Jambusar",
  "Jambusar(Kaavi)",
 ],
"Bhatinda": [
  "Bathinda",
  "Bhagta Bhai Ka",
  "Bhucho",
  "Goniana",
  "Maur",
  "Raman",
  "Rampuraphul(Nabha Mandi)",
  "Talwandi Sabo",
 ],
"Bhavnagar": [
  "Bhavnagar",
  "Mahuva(Station Road)",
  "Palitana",
  "Taleja",
 ],
"Bhilwara": [
  "Bhilwara",
  "Gangapur",
  "Gulabpura",
 ],
"Bhind": [
  "Alampur",
  "Bhind",
  "Gohad",
  "Lahar",
  "Mehgaon",
 ],
"Bhiwani": [
  "Bhiwani",
  "Ch. Dadri",
  "Loharu",
 ],
"Bhojpur": [
  "Aarah",
  "Piro",
 ],
"Bhopal": [
  "Berasia",
  "Bhopal",
 ],
"Bidar": [
  "Basava Kalayana",
  "Bidar",
 ],
"Bijapur": [
  "Bijapur",
  "Talikot",
 ],
"Bijnor": [
  "Bijnaur",
  "Chaandpur",
  "Nagina",
 ],
"Bikaner": [
  "Bikaner (F&V)",
  "Bikaner (Grain)",
  "Gudhagorji",
  "Khajuwala",
  "Lunkaransar",
  "Nokha",
  "Pugal Road (Grain)",
  "Sridungargarh",
 ],
"Bilaspur": [
  "Bilaspur",
  "Namhol(Bilaspur)",
 ],
"Birbhum": [
  "Birbhum",
  "Bolpur",
  "Rampurhat",
  "Sainthia",
 ],
"Bishnupur": [
  "Bishenpur",
 ],
"Botad": [
  "Botad",
  "Botad(Haddad)",
 ],
"Boudh": [
  "Boudh",
  "Khunthabandha",
 ],
"Bulandshahar": [
  "Anoop Shahar",
  "Buland Shahr",
  "Divai",
  "Gulavati",
  "Jahangirabad",
  "Khurja",
  "Siyana",
 ],
"Buldhana": [
  "BSK Krishi Bazar Private Ltd",
  "Buldhana(Dhad)",
  "Chikali",
  "Deoulgaon Raja",
  "Jalgaon Jamod(Aasalgaon)",
  "Khamgaon",
  "Lonar",
  "Malkapur",
  "Mehekar",
  "Nandura",
  "Sangrampur(Varvatbakal)",
  "Shegaon",
  "Sindkhed Raja",
 ],
"Bundi": [
  "Bundi",
  "Dei",
  "Keshoraipatan",
  "Sumerganj",
 ],
"Burhanpur": [
  "Burhanpur",
 ],
"Buxar": [
  "Brahmpur",
  "Buxur",
 ],
"Cachar": [
  "Fatakbazar",
 ],
"Chamba": [
  "Chamba",
 ],
"Champawat": [
  "Tanakpur",
 ],
"Chamrajnagar": [
  "Chamaraj Nagar",
  "Gundlupet",
 ],
"Chandauli": [
  "Chandoli",
 ],
"Chandigarh": [
  "Chandigarh(Grain/Fruit)",
 ],
"Chandrapur": [
  "Brahmpuri",
  "Chandrapur",
  "Chandrapur(Ganjwad)",
  "Chimur",
  "Korpana",
  "Mul",
  "Pombhurni",
  "Rajura",
  "Savali",
  "Varora",
 ],
"Chattrapati Sambhajinagar": [
  "Chattrapati Sambhajinagar",
  "Gangapur",
  "Kannad",
  "Lasur Station",
  "Paithan",
  "Sillod",
  "Vaijpur",
 ],
"Chengalpattu": [
  "Chengalpet(Uzhavar Sandhai )",
  "Guduvancheri(Uzhavar Sandhai )",
  "Jameenrayapettai(Uzhavar Sandhai )",
  "Madhuranthagam(Uzhavar Sandhai )",
  "Medavakkam(Uzhavar Sandhai )",
  "Nanganallur(Uzhavar Sandhai )",
  "Pallavaram(Uzhavar Sandhai )",
  "Thirukalukundram(Uzhavar Sandhai )",
 ],
"Chhatarpur": [
  "Bijawar",
  "Chhatarpur",
  "Harpalpur",
  "LavKush Nagar(Laundi)",
  "Naugaon",
  "Rajnagar",
 ],
"Chhindwara": [
  "Amarwda",
  "Chaurai",
  "Chhindwara",
  "Chindwara(F&V)",
  "Saunsar",
 ],
"Chhota Udaipur": [
  "Bodeliu",
  "Hadad    ",
 ],
"Chikmagalur": [
  "Bagepalli",
  "Chikkamagalore",
 ],
"Chitradurga": [
  "Challakere",
  "Chitradurga",
  "Hiriyur",
 ],
"Chitrakut": [
  "Karvi",
 ],
"Chittor": [
  "Chittoor",
  "Kalikiri",
  "Palamaner",
  "Punganur",
 ],
"Chittorgarh": [
  "Barisadri",
  "Begu",
  "Fatehnagar",
  "Kapasan",
  "Nimbahera",
  "Pratapgarh",
 ],
"Churu": [
  "Sardar Shahar",
  "Sujangarh",
 ],
"Coimbatore": [
  "Coimbatore",
  "Kurichi(Uzhavar Sandhai )",
  "Madathukulam",
  "Mettupalayam(Uzhavar Sandhai )",
  "Palladam",
  "Pollachi(Uzhavar Sandhai )",
  "RSPuram(Uzhavar Sandhai )",
  "Singanallur(Uzhavar Sandhai )",
  "Sulur",
  "Sulur(Uzhavar Sandhai )",
  "Sundarapuram(Uzhavar Sandhai )",
  "Udumalpet",
  "Vadavalli(Uzhavar Sandhai )",
 ],
"Coochbehar": [
  "Baxirhat",
  "Coochbehar",
  "Dinhata",
  "Haldibari",
  "Mathabhanga",
  "Mekhliganj",
  "Pundibari",
  "Toofanganj",
 ],
"Cuddalore": [
  "Chidambaram(Uzhavar Sandhai )",
  "Cuddalore",
  "Cuddalore(Uzhavar Sandhai )",
  "Panruti",
  "Panruti(Uzhavar Sandhai )",
  "Tittakudi",
  "Virudhachalam",
  "Viruthachalam(Uzhavar Sandhai )",
 ],
"Cuddapah": [
  "Cuddapah",
 ],
"Dahod": [
  "Dahod",
  "Dahod(Veg. Market)",
  "Davgadbaria(Piplod)",
  "Limkheda",
 ],
"Dakshin Dinajpur": [
  "Balurghat",
  "Gangarampur(Dakshin Dinajpur)",
 ],
"Damoh": [
  "Damoh",
  "Hata",
  "Patharia",
 ],
"Dantewada": [
  "Gidam",
 ],
"Darbhanga": [
  "Bahadurpur (Ekmi Ghat)",
 ],
"Darjeeling": [
  "Darjeeling",
  "Karsiyang(Matigara)",
  "Siliguri",
 ],
"Datia": [
  "Bhander",
  "Datia",
  "Sevda",
 ],
"Dausa": [
  "Bandikui",
  "Dausa",
  "Lalsot",
  "Madanganj Mahuwa",
  "Madanganj Mandawar",
  "Mandawari",
 ],
"Davangere": [
  "Davangere",
  "Harihara",
 ],
"Deeg": [
  "Deeg",
  "Kama",
  "Pahari",
 ],
"Dehradoon": [
  "Dehradoon",
  "Rishikesh",
  "Vikasnagar",
 ],
"Delhi": [
  "Azadpur",
  "Najafgarh",
  "Narela",
  "Shahdara",
 ],
"Deoria": [
  "Devariya",
 ],
"Devbhumi Dwarka": [
  "Bhanvad",
  "Jam Khambalia",
 ],
"Dewas": [
  "Bagli",
  "Dewas",
  "Haatpipliya",
  "Kannod",
  "Khategaon",
  "Sonkatch",
 ],
"Dhalai": [
  "Chowmanu",
  "Gandacharra",
  "Halahali",
  "Kulai",
  "Masli",
 ],
"Dhamtari": [
  "Belargaon",
  "Bhakhara",
  "Dhamtari",
  "Gattasilli",
  "Kurud",
 ],
"Dhar": [
  "Badnawar",
  "Dhamnod",
  "Dhar",
  "Gandhwani",
  "Kukshi",
  "Manawar",
  "Manawar(F&V)",
  "Rajgarh",
 ],
"Dharashiv(Usmanabad)": [
  "Dharashiv",
  "Kalamb (Dharashiv)",
  "Paranda",
  "Tuljapur",
  "Umarga",
 ],
"Dharmapuri": [
  "AJattihalli(Uzhavar Sandhai )",
  "Dharmapuri(Uzhavar Sandhai )",
  "Harur(Uzhavar Sandhai )",
  "Palacode(Uzhavar Sandhai )",
  "Palakode",
  "Pappireddipatti",
  "Pennagaram",
  "Pennagaram(Uzhavar Sandhai )",
 ],
"Dharwad": [
  "Hubli (Amaragol)",
 ],
"Dhenkanal": [
  "Hindol",
  "Kamakhyanagar",
 ],
"Dhubri": [
  "Chapar",
 ],
"Dhule": [
  "Dhule",
  "Dondaicha",
  "Sakri",
  "Shirpur",
 ],
"Dimapur": [
  "Dimapur",
  "Nuiland",
 ],
"Dindigul": [
  "Chinnalapatti(Uzhavar Sandhai )",
  "Dindigul",
  "Dindigul(Uzhavar Sandhai )",
  "Palani",
  "Palani(Uzhavar Sandhai )",
  "Vedasanthur(Uzhavar Sandhai )",
 ],
"Dindori": [
  "Dindori",
  "Gorakhpur",
 ],
"Durg": [
  "Durg",
  "Khamhariya",
 ],
"East Godavari": [
  "Karapa",
  "Rajahmundry",
  "Ravulapelem",
 ],
"East Jaintia Hills": [
  "Khliehriat",
 ],
"East Khasi Hills": [
  "Shillong",
 ],
"Ernakulam": [
  "Aluva",
  "Amalapuram  VFPCK",
  "Angamaly",
  "Broadway market",
  "Ernakulam",
  "Kadungallur  VFPCK",
  "Keezhampara VFPCK",
  "Koovapadi VFPCK",
  "Kothamangalam",
  "Kunnukara  VFPCK",
  "Malayattoor  VFPCK",
  "Mazhuvannur VFPCK",
  "North Paravur",
  "Perumbavoor",
  "Piravam",
  "Thiruvaniyoor  VFPCK",
  "Thrippunithura",
 ],
"Erode": [
  "Alangeyam",
  "Avalpoonthurai",
  "Boothapadi",
  "Gobichettipalayam",
  "Gobichettipalayam(Uzhavar Sandhai )",
  "Periyar Nagar(Uzhavar Sandhai )",
  "Perundurai",
  "Perundurai(Uzhavar Sandhai )",
  "Sampath Nagar(Uzhavar Sandhai )",
  "Sathiyamagalam(Uzhavar Sandhai )",
  "Sathyamangalam",
  "Sivagiri",
  "Thalavadi",
  "Thalavadi(Uzhavar Sandhai )",
  "Vellakkoil",
 ],
"Etah": [
  "Aliganj",
  "Awagarh",
  "Etah",
 ],
"Etawah": [
  "Bharthna",
  "Etawah",
  "Jasvantnagar",
 ],
"Faridabad": [
  "Faridabad",
 ],
"Faridkot": [
  "Faridkot",
  "Kotkapura",
 ],
"Farukhabad": [
  "Farukhabad",
  "Kamlaganj",
  "Kayamganj",
  "Mohamadabad",
 ],
"Fatehabad": [
  "Jakhal",
  "Ratia",
  "Tohana",
  "Tohana(New Veg Market)",
 ],
"Fatehgarh": [
  "Bassi Pathana",
  "Khamano",
  "Sirhind",
 ],
"Fatehpur": [
  "Bindki",
  "Fatehpur",
  "Jahanabad",
  "Khaga",
  "Kishunpur",
 ],
"Fazilka": [
  "Fazilka",
  "Jalalabad",
 ],
"Ferozpur": [
  "Firozepur City",
  "Mallanwala",
  "Mamdot",
  "Zira",
 ],
"Firozabad": [
  "Firozabad",
  "Shikohabad",
  "Sirsaganj",
  "Tundla",
 ],
"Gadag": [
  "Gadag",
  "Laxmeshwar",
  "Mundaragi",
  "Rona",
 ],
"Gadchiroli": [
  "Armori",
  "Gandchiroli",
 ],
"Gajapati": [
  "Kasinagar",
  "Parlakhemundi",
 ],
"Gandhinagar": [
  "Dehgam",
  "Dehgam(Rekhiyal)",
  "Kalol",
  "Kalol(Veg,Market,Kalol)",
  "Mansa",
  "Mansa(Manas Veg Yard)",
 ],
"Ganganagar": [
  "Anupgarh",
  "Gajsinghpur",
  "Jaitsar",
  "Kesarisinghpur",
  "Lalgarh Jatan",
  "Padampur",
  "Raisingh Nagar",
  "Rawla",
  "Sadulshahar",
  "Sri Karanpur",
  "Sri Vijayanagar",
  "Sriganganagar (F&V)",
  "Sriganganagar (Grain)",
  "Suratgarh",
 ],
"Ganjam": [
  "Digapahandi",
  "Hinjilicut",
 ],
"Garhwal (Pauri)": [
  "Kotadwara",
 ],
"Gariyaband": [
  "Devbhog",
  "Rajim",
 ],
"Gautam Budh Nagar": [
  "Dadri",
  "Dankaur",
 ],
"Ghaziabad": [
  "Ghaziabad",
  "Hapur",
  "Noida",
 ],
"Ghazipur": [
  "Gazipur",
 ],
"Gir Somnath": [
  "Kodinar",
  "Talalagir",
  "Veraval",
 ],
"Goalpara": [
  "Lakhipur",
 ],
"Gomati": [
  "Garjee",
  "Nutanbazar",
  "Silachhari",
 ],
"Gonda": [
  "Gonda",
  "Karnailganj",
  "Nawabganj",
 ],
"Gondiya": [
  "Gondiya",
 ],
"Gorakhpur": [
  "Chorichora",
  "Gorakhpur",
  "Sehjanwa",
 ],
"Guna": [
  "Aron",
  "Binaganj",
  "Guna",
  "Kumbhraj",
  "Maksudangarh",
  "Raghogarh",
 ],
"Guntur": [
  "Duggirala",
 ],
"Gurdaspur": [
  "Batala",
  "Dera Baba Nanak",
  "Dhariwal",
  "Dinanagar",
  "F.G.Churian",
  "Gurdaspur",
  "Kalanaur",
 ],
"Gurgaon": [
  "Farukh Nagar",
  "Gurgaon",
  "Pataudi",
  "Sohna",
 ],
"Gwalior": [
  "Bhitarwar",
  "Dabra",
  "Lashkar",
 ],
"Hamirpur": [
  "Bharuasumerpur",
  "Hamirpur",
  "Hamirpur(Nadaun)",
  "Maudaha",
  "Muskara",
  "Raath",
 ],
"Hanumangarh": [
  "Bhadara",
  "Goluwala",
  "Hanumangarh",
  "Hanumangarh Town",
  "Hanumangarh(Urlivas)",
  "Nohar",
  "Pilibanga",
  "Rawatsar",
  "Sangriya",
  "Suratgarh",
 ],
"Hapur": [
  "Gazipur",
  "Jangipura",
  "Yusufpur",
 ],
"Harda": [
  "Harda",
  "Khirakiya",
  "Sirali",
  "Timarni",
  "Timarni(F&V)",
 ],
"Hardoi": [
  "Hardoi",
  "Madhoganj",
  "Sandi",
  "Sandila",
  "Shahabad(New Mandi)",
 ],
"Haridwar": [
  "Bhagwanpur(Naveen Mandi Sthal)",
  "Haridwar Union",
  "Lakshar",
  "Manglaur",
  "Roorkee",
 ],
"Hassan": [
  "Arasikere",
  "Channarayapatna",
  "Hassan",
 ],
"Hathras": [
  "Haathras",
  "Shadabad",
  "Sikandraraau",
 ],
"Haveri": [
  "Hirekerur",
  "Savanur",
  "Shiggauv",
 ],
"Hingoli": [
  "Akhadabalapur",
  "Hingoli",
  "Sengoan",
 ],
"Hissar": [
  "Adampur",
  "Barwala(Hisar)",
  "Hansi",
  "Hissar",
  "Uklana",
 ],
"Hooghly": [
  "Champadanga",
  "Kalipur",
  "Pandua",
  "Sheoraphuly",
 ],
"Hoshangabad": [
  "Banapura",
  "Itarsi",
  "Pipariya",
  "Semriharchand",
 ],
"Hoshiarpur": [
  "Dasuya",
  "Garh Shankar",
  "Garh Shankar(Mahalpur)",
  "GarhShankar (Kotfatuhi)",
  "Hoshiarpur",
  "Hoshiarpur(Sham Churasi)",
  "Mukerian",
  "Mukerian(Talwara)",
  "Tanda Urmur",
 ],
"Howrah": [
  "Ramkrishanpur(Howrah)",
  "Uluberia",
 ],
"Hyderabad": [
  "Bowenpally",
  "Erragadda(Rythu Bazar)",
  "Gaddiannaram",
  "Gudimalkapur",
  "L B Nagar",
  "Mahboob Manison",
 ],
"Idukki": [
  "Adimali",
  "Kattappana",
  "Kodikulam  VFPCK",
  "Munnar",
  "Nedumkandam",
  "Pazhayarikandam  VFPCK",
  "Thodupuzha",
  "Udumbannoor  VFPCK",
  "Vandiperiyar",
 ],
"Imphal East": [
  "Lamlong Bazaar",
 ],
"Imphal West": [
  "Imphal",
 ],
"Indore": [
  "Gautampura",
  "Indore",
  "Mhow",
  "Mhow(F&V)",
  "Sanwer",
 ],
"Jabalpur": [
  "Jabalpur",
  "Paatan",
  "Sehora",
  "Shahpura Bhitoni (F&V)",
  "Shahpura(Jabalpur)",
 ],
"Jaipur": [
  "Bassi",
  "Chaksu",
  "Chomu (F&V)",
  "Chomu (Grain)",
  "Jaipur (F&V)",
  "Kishan Renwal(Fulera)",
  "Kotputli",
  "Sambhar (Kishangarh renwal)",
 ],
"Jaipur Rural": [
  "Bagru",
  "Bassi",
  "Chomu (F&V)",
  "Chomu (Grain)",
 ],
"Jalana": [
  "Ambad (Vadigodri)",
  "Ashti(Jalna)",
  "Bhokardan(Pimpalgaon Renu)",
  "Jafrabad",
  "Jalana",
  "Mantha",
  "Partur",
 ],
"Jalandhar": [
  "Bilga",
  "Jalandhar City(Jalandhar)",
  "Lohian Khas",
  "Mehatpur",
  "Nakodar",
  "Noor Mehal",
  "Phillaur(Apra Mandi)",
  "Shahkot",
 ],
"Jalaun (Orai)": [
  "Ait",
  "Jalaun",
  "Kadaura",
  "Konch",
  "Madhogarh",
  "Orai",
 ],
"Jalgaon": [
  "Amalner",
  "Bhusaval",
  "Chalisgaon",
  "Chopada",
  "Jalgaon",
  "Jalgaon(Masawat)",
  "Pachora",
  "Raver",
  "Yawal",
 ],
"Jalore": [
  "Bhinmal",
  "Jalore",
 ],
"Jalpaiguri": [
  "Belacoba",
  "Dhupguri",
  "Jalpaiguri Sadar",
  "Moynaguri",
 ],
"Jammu": [
  "Akhnoor",
  "Batote",
  "Narwal Jammu (F&V)",
 ],
"Jamnagar": [
  "Dhrol",
  "Jam Jodhpur",
  "Jamnagar",
 ],
"Jamui": [
  "Jamui",
 ],
"Janjgir": [
  "Amadula",
  "Baradwar",
  "Jaijaipur",
 ],
"Jaunpur": [
  "Jaunpur",
  "Mugrabaadshahpur",
  "Shahganj",
 ],
"Jehanabad": [
  "Jehanabad",
 ],
"Jhabua": [
  "Jhabua",
  "Petlawad",
  "Petlawad(F&V)",
  "Thandla",
 ],
"Jhajar": [
  "Bahadurgarh",
  "Jhajjar",
 ],
"Jhalawar": [
  "Bhawani Mandi",
  "Choumahla",
  "Dag",
  "Iklera",
  "Jhalarapatan",
  "Khanpur",
  "Manohar Thana",
 ],
"Jhansi": [
  "Baruwasagar",
  "Chirgaon",
  "Gurusarai",
  "Jhansi",
  "Jhansi (Grain)",
  "Mauranipur",
  "Moth",
 ],
"Jhargram": [
  "Jhargram",
 ],
"Jharsuguda": [
  "Jharsuguda",
 ],
"Jhunjunu": [
  "Jhunjhunu",
  "Nawalgarh",
 ],
"Jind": [
  "Jind",
  "Jullana",
  "Narwana",
  "New Grain Market , Jind",
  "Pillukhera",
  "Safidon",
  "Uchana",
 ],
"Jodhpur": [
  "Bhagat Ki Kothi",
  "Bhagat Kii Phalodi",
  "Bilara",
  "Jodhpur (F&V)",
  "Jodhpur (Grain)",
  "Jodhpur(F&V)(Paota)",
 ],
"Jodhpur Rural": [
  "Bilara",
 ],
"Junagarh": [
  "Bhesan",
  "Junagadh",
  "Manavdar",
  "Mangrol",
  "Visavadar",
 ],
"Kabirdham": [
  "Kawardha",
 ],
"Kachchh": [
  "Bachau",
  "Bhuj",
  "Mundra",
  "Rapar",
 ],
"Kaithal": [
  "Cheeka",
  "Dhand",
  "Pai",
  "Pundri",
  "Siwan",
 ],
"Kaithar": [
  "Gerabari, Korha Block",
 ],
"Kakching": [
  "Kakching Market",
 ],
"Kalahandi": [
  "Kesinga",
 ],
"Kalburgi": [
  "Chincholi",
  "Chittapur",
  "Kalburgi",
 ],
"Kalimpong": [
  "Kalimpong",
 ],
"Kallakuruchi": [
  "Kallakurichi(Uzhavar Sandhai )",
  "Sankarapuram(Uzhavar Sandhai )",
 ],
"Kamrup": [
  "Pamohi(Garchuk)",
 ],
"Kancheepuram": [
  "Acharapakkam",
  "Chengalpattu",
  "Kancheepuram(Uzhavar Sandhai )",
  "Kundrathur(Uzhavar Sandhai )",
  "Padappai(Uzhavar Sandhai )",
 ],
"Kangra": [
  "Dharamshala",
  "Kangra",
  "Kangra(Baijnath)",
  "Kangra(Jaisinghpur)",
  "Kangra(Jassour)",
  "Kangra(Nagrota Bagwan)",
  "Palampur",
 ],
"Kanker": [
  "Amoda",
  "Antagarh",
  "Bardewri",
  "Bhanupratappur",
  "Dudhawa",
  "Kanker",
  "Korar",
  "Lakhanpuri",
  "Narharpur",
  "Pakhanjur",
  "Sambalpur",
  "Sarona",
 ],
"Kannuj": [
  "Chhibramau",
  "Kannauj",
 ],
"Kannur": [
  "Chavassery VFPCK",
  "Irikkur",
  "Kannur",
  "Kuthuparambu",
  "Mattannur  VFPCK",
  "Payyannur",
  "Taliparamba",
  "Thalasserry",
 ],
"Kanpur": [
  "Choubepur",
  "Kanpur(Grain)",
  "Uttaripura",
  "Varipaal",
 ],
"Kanpur Dehat": [
  "Jhijhank",
  "Pukharayan",
  "Rura",
 ],
"Karauli": [
  "Hindoun",
 ],
"Karbi Anglong": [
  "Manja",
 ],
"Karimnagar": [
  "Choppadandi",
  "Dharmapuri",
  "Dharmaram",
  "Gangadhara",
  "Huzzurabad",
  "Jagtial",
  "Jammikunta",
  "Karimnagar",
  "Karimnagar(Rythu Bazar)",
  "Kataram",
  "Kathalapur",
  "Mallial(Cheppial)",
  "Manakodur",
  "Medipally",
  "Metpally",
  "Vemulawada",
 ],
"Karnal": [
  "Gharaunda",
  "Indri",
  "New Grain Market(main), Karnal",
 ],
"Karur": [
  "Karur(Uzhavar Sandhai )",
  "Kulithalai(Uzhavar Sandhai )",
  "Pallapatti (Uzhavar Sandhai )",
  "Velayuthampalayam(Uzhavar Sandhai )",
 ],
"Karwar(Uttar Kannad)": [
  "Haliyala",
  "Sirsi",
  "Yellapur",
 ],
"Kasargod": [
  "Kanjangadu",
  "Kasargod",
  "Madikai  VFPCK",
  "Manjeswaram",
  "Neeleswaram",
  "Pullur Periya  VFPCK",
 ],
"Kasganj": [
  "Kasganj",
 ],
"Kathua": [
  "Kathua",
 ],
"Katni": [
  "Katni",
 ],
"Kaushambi": [
  "Bharwari",
  "Manjhanpur",
 ],
"Kendrapara": [
  "Chatta Krushak Bazar",
  "Kendrapara",
  "Kendrapara(Marshaghai)",
  "Pattamundai",
 ],
"Keonjhar": [
  "Keonjhar",
  "Saharpada",
 ],
"Khairthal Tijara": [
  "Khairthal",
 ],
"Khammam": [
  "Bhadrachalam",
  "Burgampadu",
  "Charla",
  "Dammapet",
  "Khammam",
  "Kothagudem",
  "Madhira",
  "Sattupalli (ramalayam),RBZ",
  "Yellandu",
 ],
"Khandwa": [
  "Badwah(F&V)",
  "Harsood",
  "Khandwa",
  "Mundi",
  "Pandhana",
  "Sanawad(F&V)",
 ],
"Khargone": [
  "Badwaha",
  "Bedia",
  "Bhikangaon",
  "Karhi",
  "Kasrawad",
  "Khargone",
  "Sanawad",
 ],
"Kheda": [
  "Kapadvanj",
  "Matar(Limbasi)",
  "Nadiad",
  "Nadiyad(Chaklasi)",
  "Nadiyad(Piplag)",
 ],
"Khiri (Lakhimpur)": [
  "Maigalganj",
  "Mohammdi",
  "Tikonia",
 ],
"Khowai": [
  "Kalyanpur",
  "Teliamura",
 ],
"Khurda": [
  "Aiginia Mandi",
  "Balugaon",
  "Damana Hat",
  "Jatni",
 ],
"Kiphire": [
  "Kipheri",
 ],
"Kishanganj": [
  "Bahadurganj",
  "Thakurganj",
 ],
"Kohima": [
  "Jalukie",
  "Kohima",
 ],
"Kolar": [
  "Bangarpet",
  "Chickkaballapura",
  "Chintamani",
  "Gowribidanoor",
  "Kolar",
  "Mulabagilu",
 ],
"Kolhapur": [
  "Kolhapur",
  "Vadgaonpeth",
 ],
"Kolkata": [
  "Bara Bazar (Posta Bazar)",
  "Mechua",
  "Sealdah Koley Market",
 ],
"Kollam": [
  "Anchal",
  "Anchal VFPCK",
  "Chathanoor",
  "Chengamanad  VFPCK",
  "Elamad  VFPCK",
  "Kollam",
  "Kottarakkara",
  "Nedumpaikulam  VFPCK",
  "Nedumpana  VFPCK",
  "Neduvathoor  VFPCK",
  "Punalur",
  "Punalur VFPCK",
  "Sasthamkotta",
  "Sasthamkotta VFPCK",
  "Sooranad  VFPCK",
 ],
"Kondagaon": [
  "Bededonger",
  "Dhanora",
  "Gamhari",
  "Hirapur",
  "Keshkal",
  "Kondagoan",
  "Makdi",
  "Mardapal",
  "Pharasgaon",
  "Vishrampur",
 ],
"Koppal": [
  "Gangavathi",
  "Gangavathi(Karatagi)",
  "Koppal",
  "Kustagi",
  "Yalburga",
 ],
"Koraput": [
  "Koraput",
  "Koraput(Semilguda)",
 ],
"Korba": [
  "Katghora",
 ],
"Koria": [
  "Manendragarh",
 ],
"Kota": [
  "Itawa",
  "Kota",
  "Kota (F&V)",
  "Ramganjmandi",
 ],
"Kotputli- Behror": [
  "Bansoor",
  "Kotputli",
 ],
"Kottayam": [
  "Athirampuzha",
  "Ettumanoor",
  "Kanjirappally",
  "Kottayam",
  "Kuriem  VFPCK",
  "Kuruppanthura",
  "Mannackanad  VFPCK",
  "Mutholy  VFPCK",
  "Pala",
  "Pampady",
  "Thalayolaparambu",
  "Thottuva  VFPCK",
  "Vayala  VFPCK",
  "Vempally  VFPCK",
 ],
"Kozhikode(Calicut)": [
  "Kallachi",
  "Mavoor  VFPCK",
  "Mukkam  VFPCK",
  "Mukkom",
  "Palayam",
  "Perambra",
  "Quilandy",
  "Thamarassery",
  "Vellannur  VFPCK",
  "Vengeri(Kozhikode)",
 ],
"Krishna": [
  "Tiruvuru",
 ],
"Krishnagiri": [
  "Avallapalli(Uzhavar Sandhai )",
  "Denkanikottai",
  "Denkanikottai(Uzhavar Sandhai )",
  "Hosur",
  "Hosur(Uzhavar Sandhai )",
  "Kaveripattinam(Uzhavar Sandhai )",
  "Krishnagiri",
  "Krishnagiri(Uzhavar Sandhai )",
 ],
"Kullu": [
  "Bhuntar",
  "Kullu",
 ],
"Kurnool": [
  "Adoni",
  "Atmakur",
  "Banaganapalli",
  "Kurnool",
  "Nandikotkur",
  "Pattikonda",
 ],
"Kurukshetra": [
  "Babain",
  "Iamailabad",
  "Ladwa",
  "Pehowa",
  "Pipli",
  "Shahabad",
  "Thanesar",
 ],
"Kushinagar": [
  "Tamkuhi road",
 ],
"Lakhimpur": [
  "Golagokarnath",
  "Lakhimpur",
  "Paliakala",
 ],
"Lalitpur": [
  "Lalitpur",
  "Mehrauni",
 ],
"Latur": [
  "Ahmedpur",
  "Aurad Shahajani",
  "Ausa",
  "Chakur",
  "Jalkot",
  "Latur",
  "Latur(Murud)",
  "Nilanga",
  "Udgir",
 ],
"Longleng": [
  "Longleng",
 ],
"Lucknow": [
  "Lucknow",
 ],
"Ludhiana": [
  "Doraha",
  "Jagraon",
  "Khanna",
  "Ludhiana",
  "Machhiwara",
  "Sahnewal",
  "Samrala",
  "Sidhwan Bet",
 ],
"MORIGAON": [
  "Jagiroad Dry Fish Market",
  "Laharighat",
 ],
"Madhepura": [
  "Murliganj",
 ],
"Madhubani": [
  "Jahajharpur",
  "Jainagar",
 ],
"Madurai": [
  "Anaiyur(Uzhavar Sandhai )",
  "Anna nagar(Uzhavar Sandhai )",
  "Chokkikulam(Uzhavar Sandhai )",
  "Madurai",
  "Melur",
  "Melur(Uzhavar Sandhai )",
  "Palanganatham(Uzhavar Sandhai )",
  "Thirumangalam(Uzhavar Sandhai )",
  "Usilampatty",
 ],
"Maharajganj": [
  "Anandnagar",
  "Gadaura",
  "Nautnava",
  "Partaval",
 ],
"Mahasamund": [
  "Bhoring",
  "Jhalap",
  "Mahasamund",
  "Pithoura",
  "Sarayapali",
 ],
"Mahbubnagar": [
  "Achampet",
  "Alampur",
  "Badepalli",
  "Devarakadra",
  "Gadwal",
  "Gadwal(Lezza)",
  "Kalwakurthy",
  "Mahabubnagar(Rythu Bazar)",
  "Nagarkurnool",
  "Nagarkurnool(Talkapalli)",
  "Narayanpet",
  "Shadnagar",
  "Wanaparthy Road",
  "Wanaparthy Road(Prbbair)",
  "Wanaparthy town",
 ],
"Mahendragarh-Narnaul": [
  "Ateli",
  "Khanina",
  "Mohindergarh",
  "Narnaul",
 ],
"Mahoba": [
  "Mahoba",
 ],
"Mainpuri": [
  "Ghiraur",
  "Mainpuri",
 ],
"Malappuram": [
  "Kannamangalam  VFPCK",
  "Kodakkad  VFPCK",
  "Kondotty",
  "Kottakkal",
  "Manjeri",
  "Moothedam  VFPCK",
  "Parappanangadi",
  "Parappanangadi VFPCK",
  "Perinthalmanna",
  "Thalappara  VFPCK",
  "Thirurrangadi",
 ],
"Malda": [
  "English Bazar",
  "Gajol",
  "Samsi",
 ],
"Malkangiri": [
  "Malkangiri(Korakunda)",
 ],
"Mandi": [
  "Dhanotu (Mandi)",
  "Mandi(Mandi)",
  "Mandi(Takoli)",
 ],
"Mandla": [
  "Bichhiya",
  "Mandla",
 ],
"Mandsaur": [
  "Bhanpura",
  "Daloda",
  "Mandsaur",
  "Piplya",
  "Shamgarh",
  "Sitmau",
  "Suvasra",
 ],
"Mandya": [
  "Mandya",
  "Nagamangala",
 ],
"Mangalore(Dakshin Kannad)": [
  "Bantwala",
  "Sulya",
 ],
"Mansa": [
  "Bareta",
  "Budalada",
  "Mansa",
 ],
"Mathura": [
  "Kosikalan",
  "Mathura",
 ],
"Mau(Maunathbhanjan)": [
  "Doharighat",
  "Kopaganj",
 ],
"Mayurbhanja": [
  "Baripada",
  "Chuliaposi",
  "Karanjia",
  "Saraskana",
  "Udala",
 ],
"Medak": [
  "Dubbak",
  "Narsapur",
  "Siddipet",
  "Vantamamidi",
  "Zaheerabad",
 ],
"Medinipur(E)": [
  "Egra/contai",
  "Kolaghat",
  "Tamluk (Medinipur E)",
 ],
"Medinipur(W)": [
  "Garbeta(Medinipur)",
  "Ghatal",
  "Medinipur(West)",
 ],
"Meerut": [
  "Meerut",
 ],
"Mehsana": [
  "Kadi",
  "Mehsana",
  "Mehsana(Jornang)",
  "Mehsana(Mehsana Veg)",
  "Unava",
  "Unjha",
  "Vijapur",
  "Vijapur(Kukarvada)",
  "Visnagar",
 ],
"Mewat": [
  "FerozpurZirkha(Nagina)",
  "Nuh",
  "Punhana",
 ],
"Mirzapur": [
  "Ahirora",
  "Mirzapur",
 ],
"Moga": [
  "Baghapurana",
  "Kot ise Khan",
  "Moga",
 ],
"Mohali": [
  "Banur",
  "Dera Bassi",
  "Kharar",
  "Lalru",
 ],
"Mokokchung": [
  "Mangkolemba",
  "Mokokchung Town",
  "Tuli",
 ],
"Mon": [
  "Mon",
  "Naginimora",
 ],
"Morbi": [
  "Halvad",
  "Morbi",
  "Vankaner",
  "Vankaner(Sub yard)",
 ],
"Morena": [
  "Morena",
  "Porsa",
  "Sabalgarh",
 ],
"Muktsar": [
  "Bariwala",
  "Giddarbaha",
  "Malout",
  "Malout (Kilianwali)",
  "Muktsar",
 ],
"Mumbai": [
  "Mumbai",
  "Vashi New Mumbai",
 ],
"Mungeli": [
  "Munguli",
 ],
"Murshidabad": [
  "Beldanga",
  "Jangipur",
  "Jiaganj",
  "Kandi",
  "Kasimbazar",
  "Lalbagh",
 ],
"Murum": [
  "Dharashiv",
 ],
"Muzaffarnagar": [
  "Muzzafarnagar",
  "Shahpur",
 ],
"Muzaffarpur": [
  "Bhagwanpur Mandi",
 ],
"Mysore": [
  "Mysore (Bandipalya)",
  "Nanjangud",
  "Santhesargur",
 ],
"Nadia": [
  "Bethuadahari",
  "Chakdah",
  "Kalyani",
  "Karimpur",
  "Nadia",
  "Ranaghat",
 ],
"Nagapattinam": [
  "Mayiladuthurai(Uzhavar Sandhai )",
  "Nagapattinam(Uzhavar Sandhai )",
  "Sirkali",
  "Sirkali(Uzhavar Sandhai )",
 ],
"Nagaur": [
  "Merta City",
  "Nagaur",
  "Nagour(FV)",
 ],
"Nagercoil (Kannyiakumari)": [
  "Myladi(Uzhavar Sandhai )",
  "Thoduvetty",
  "Vadaseri",
 ],
"Nagpur": [
  "Hingna",
  "Kalmeshwar",
  "Kamthi",
  "Katol",
  "MS Kalpana Agri Commodities Marketing",
  "Mandhal",
  "Nagpur",
  "Parshiwani",
  "Ramtek",
  "Savner",
  "Umared",
 ],
"Nalbari": [
  "Nalbari",
 ],
"Nalgonda": [
  "Aler",
  "Devarakonda",
  "Devarkonda(Dindi)",
  "Devarkonda(Mallepalli)",
  "Halia",
  "Huzumnagar(Garidepally)",
  "Huzurnagar(Matampally)",
  "Kodad",
  "Miryalaguda",
  "Mothkur",
  "Neredcherla",
  "Nidamanoor",
  "Ramannapet",
  "Suryapeta",
  "Tirumalagiri",
  "Venkateswarnagar",
  "Voligonda",
 ],
"Namakkal": [
  "Kumarapalayam(Uzhavar Sandhai )",
  "Mohanur(Uzhavar Sandhai )",
  "Namakkal",
  "Namakkal(Uzhavar Sandhai )",
  "Paramathivelur(Uzhavar Sandhai )",
  "Rasipuram",
  "Rasipuram(Uzhavar Sandhai )",
  "Tiruchengode",
  "Velur",
 ],
"Nanded": [
  "Bhokar",
  "Himalyatnagar",
  "Mudkhed",
 ],
"Nandurbar": [
  "Dhadgaon",
  "Nandurbar",
  "Navapur",
  "Shahada",
  "Taloda",
 ],
"Nanital": [
  "Haldwani",
 ],
"Narayanpur": [
  "Narayanpur",
 ],
"Narmada": [
  "Rajpipla",
 ],
"Narsinghpur": [
  "Gadarwada",
  "Gotegaon",
  "Kareli",
  "Narsinghpur",
  "Tendukheda",
 ],
"Nashik": [
  "Chandvad",
  "Devala",
  "Dindori",
  "Ghoti",
  "Kalvan",
  "Lasalgaon",
  "Lasalgaon(Niphad)",
  "Lasalgaon(Vinchur)",
  "Malegaon",
  "Mankamneshwar Farmar Producer CoLtd Sanchalit Mank",
  "Manmad",
  "Nampur",
  "Nandgaon",
  "Nasik",
  "Pimpalgaon",
  "Pimpalgaon Baswant(Saykheda)",
  "Satana",
  "Shree Rameshwar Krushi Market ",
  "Sinner",
  "Umrane",
  "Yeola",
 ],
"Navsari": [
  "Bilimora",
  "Chikhali",
  "Navsari",
  "Vansda",
 ],
"Nawanshahr": [
  "Banga",
  "Nawan Shahar(MandiRaho)",
  "Nawanshahar",
 ],
"Nayagarh": [
  "Bahadajholla",
 ],
"Neemuch": [
  "Javad",
  "Manasa",
  "Neemuch",
 ],
"Nizamabad": [
  "Bhiknoor",
  "Bichkunda",
  "Nizamabad",
 ],
"North 24 Parganas": [
  "Barasat",
  "Habra",
 ],
"North Goa": [
  "Mapusa",
  "Pernem",
  "Sanquelim",
 ],
"North Tripura": [
  "Dasda",
  "Kadamtala",
  "Kanchanpur",
  "Panisagar",
 ],
"North and Middle Andaman ": [
  "Mayabandar",
 ],
"Nuapada": [
  "Khariar",
  "Khariar Road",
 ],
"Palakad": [
  "Kizhakkancheri VFPCK",
  "Koduvayoor",
  "Kollengode",
  "Malampuzha VFPCK",
  "Palakkad",
  "Pattambi",
  "Vadakarapathy VFPCK",
  "Vadakkenchery",
  "Vaniyamkulam  VFPCK",
  "Vithinasserri VFPCK",
  "vadakarapathy",
 ],
"Pali": [
  "Jaitaran",
  "Rani",
  "Sumerpur",
 ],
"Palwal": [
  "Hodal",
  "Palwal",
 ],
"Panchkula": [
  "Barwala",
  "New Grain Market , Panchkula",
  "Raipur Rai",
 ],
"Panchmahals": [
  "Godhra",
  "Godhra(Timbaroad)",
  "Gogamba",
  "Morva Hafad",
 ],
"Panipat": [
  "Madlauda",
  "Panipat",
  "Samalkha",
 ],
"Panna": [
  "Ajaygarh",
  "Panna",
  "Simariya",
 ],
"Parbhani": [
  "Gangakhed",
  "Jintur",
  "Pathari",
  "Shree Salasar Krushi Bazar ",
  "Sonpeth",
  "Tadkalas",
 ],
"Paschim Bardhaman": [
  "Asansol",
  "Durgapur",
 ],
"Patan": [
  "Harij",
  "Patan",
  "Radhanpur",
  "Sami",
  "Siddhpur",
 ],
"Pathanamthitta": [
  "Ezhamkulam",
  "Kalanjoor  VFPCK",
  "Kuttoor",
  "Mallappally  VFPCK",
  "Mezhuveli  VFPCK",
  "Naranganam  VFPCK",
  "Omalloor",
  "Pallikkal  VFPCK",
  "Pandalam",
  "Pandalam Thekkekkara  VFPCK",
  "Parakkodu",
  "Pramadom VFPCK",
  "Puramattom VFPCK",
  "Ranniangadi",
  "Seethathode  VFPCK",
 ],
"Patiala": [
  "Bhadson",
  "Dakala",
  "Dudhansadhan",
  "Nabha",
  "Patiala(New Anaj Mandi)",
  "Patran",
  "Rajpura",
  "Samana",
 ],
"Patna": [
  "Danapur",
 ],
"Perambalur": [
  "Perambalur(Uzhavar Sandhai )",
 ],
"Phek": [
  "Phek",
 ],
"Pillibhit": [
  "Pilibhit",
  "Puranpur",
  "Vishalpur",
 ],
"Pondicherry": [
  "Madagadipet",
  "Thattanchavady",
 ],
"Porbandar": [
  "Porbandar",
 ],
"Pratapgarh": [
  "Chhotisadri",
  "Pratapgarh",
 ],
"Prayagraj": [
  "Ajuha",
  "Allahabad",
  "Jasra",
  "Sirsa",
 ],
"Pudukkottai": [
  "Alangudi(Uzhavar Sandhai )",
  "Aranthangi(Uzhavar Sandhai )",
  "Gandarvakottai(Uzhavar Sandhai )",
  "Karambakkudi(Uzhavar Sandhai )",
  "Pudukottai",
  "Pudukottai(Uzhavar Sandhai )",
  "Viralimalai(Uzhavar Sandhai )",
 ],
"Pulwama": [
  "Pulwama (F&V)",
  "Shopian",
 ],
"Pune": [
  "Baramati",
  "Bhor",
  "Dound",
  "Junnar(Narayangaon)",
  "Junnar(Otur)",
  "Khed(Chakan)",
  "Manchar",
  "Pune",
  "Pune(Khadiki)",
  "Pune(Manjri)",
  "Pune(Moshi)",
  "Pune(Pimpri)",
  "Shirur",
 ],
"Purba Bardhaman": [
  "Burdwan",
  "Guskara",
  "Kalna",
  "Katwa",
  "Memari",
 ],
"Puri": [
  "Dumal",
  "Nimapara",
 ],
"Purnea": [
  "Bhawanipur",
 ],
"Puruliya": [
  "Balarampur",
  "Purulia",
 ],
"Raebarelli": [
  "Bachranwa",
  "Jayas",
  "Lalganj",
  "Raibareilly",
 ],
"Raichur": [
  "Lingasugur",
  "Raichur",
 ],
"Raigad": [
  "Alibagh",
  "Karjat(Raigad)",
  "Mangaon",
  "Murud",
  "Panvel",
  "Pen",
 ],
"Raigarh": [
  "Baramkela",
  "Gharghoda",
 ],
"Raipur": [
  "Arang",
  "Navapara",
  "Neora",
  "Raipur",
 ],
"Raisen": [
  "Bareli",
  "Begamganj",
  "Gairatganj",
  "Obedullaganj",
  "Raisen",
  "Silvani",
  "Udaipura",
 ],
"Rajasamand": [
  "Rajsamand",
 ],
"Rajgarh": [
  "Biaora",
  "Jeerapur",
  "Khilchipur",
  "Khujner",
  "Kurawar",
  "Machalpur",
  "Narsinghgarh",
  "Pachaur",
  "Sarangpur",
 ],
"Rajkot": [
  "Dhoraji",
  "Gondal",
  "Gondal(Veg.market Gondal)",
  "Jasdan",
  "Jetpur(Dist.Rajkot)",
  "Rajkot",
  "Rajkot(Veg.Sub Yard)",
  "Upleta",
 ],
"Rajnandgaon": [
  "Kheragarh",
  "Rajnandgaon",
 ],
"Rajouri": [
  "Rajouri (F&V)",
 ],
"Rajsamand": [
  "Rajsamand",
 ],
"Ramanathapuram": [
  "Paramakudi",
  "Paramakudi(Uzhavar Sandhai )",
  "Ramanathapuram(Uzhavar Sandhai )",
 ],
"Rampur": [
  "Milak",
  "Rampur",
  "Shahabad",
  "Tanda(Rampur)",
  "Vilaspur",
 ],
"Ranga Reddy": [
  "Chevella",
  "Ibrahimputnam",
  "Kukatpally(Rythu Bazar)",
  "Mehndipatnam(Rythu Bazar)",
  "Narsingi",
  "Narsingi(Babbuguda)",
  "Pargi",
  "Ramakrisnapuram,RBZ",
  "Tanduru",
  "Vikarabad",
 ],
"Ranipet": [
  "Arcot(Uzhavar Sandhai )",
  "Ranipettai(Uzhavar Sandhai )",
 ],
"Ratlam": [
  "A lot",
  "Jaora",
  "Jawra(F&V)",
  "Ratlam",
  "Sailana",
  "Taal",
 ],
"Ratnagiri": [
  "Ratnagiri (Nachane)",
 ],
"Rayagada": [
  "Gunpur",
  "Rayagada",
  "Rayagada(Muniguda)",
 ],
"Rewa": [
  "Baikunthpur",
  "Chaakghat",
  "Hanumana",
  "Rewa",
 ],
"Rewari": [
  "Kosli",
  "Rewari",
 ],
"Rohtak": [
  "Meham",
  "Rohtak",
  "Sampla",
 ],
"Rohtas": [
  "Kochas (Balthari)",
  "Natwar",
  "Nokha",
 ],
"Ropar (Rupnagar)": [
  "Chamkaur Sahib",
  "Morinda",
  "Ropar",
 ],
"Sabarkantha": [
  "Bhiloda",
  "Dhansura",
  "Himatnagar",
  "Khedbrahma",
  "Meghraj(Radlavada)",
  "Modasa",
  "Modasa(Tintoi)",
  "Talod",
  "Vadali",
  "Vijaynagar(Kundlakap)",
 ],
"Sagar": [
  "Bamora",
  "Banda",
  "Bina",
  "Deori",
  "Garhakota",
  "Khurai",
  "Khurai(F&V)",
  "Rahatgarh",
  "Rehli",
  "Sagar",
 ],
"Saharanpur": [
  "Chutmalpur",
  "Deoband",
  "Gangoh",
  "Rampurmaniharan",
  "Saharanpur",
 ],
"Salem": [
  "Ammapet(Uzhavar Sandhai )",
  "Athur(Uzhavar Sandhai )",
  "Attayampatti(Uzhavar Sandhai )",
  "Attur",
  "Edapadi (Uzhavar Sandhai )",
  "Edappadi",
  "Elampillai(Uzhavar Sandhai )",
  "Gangavalli",
  "Hasthampatti(Uzhavar Sandhai )",
  "Jalagandapuram(Uzhavar Sandhai )",
  "Kolathur",
  "Konganapuram",
  "Mettur(Uzhavar Sandhai )",
  "Salem",
  "Sooramangalam(Uzhavar Sandhai )",
  "Thammampati",
  "Thammampatti (Uzhavar Sandhai )",
  "Thathakapatti(Uzhavar Sandhai )",
 ],
"Samastipur": [
  "Tajpur",
 ],
"Sambalpur": [
  "Kuchinda",
 ],
"Sambhal": [
  "Bhehjoi",
  "Chandausi",
  "Muradabad",
  "Sambhal",
 ],
"Sanchore": [
  "Raniwara",
 ],
"Sangli": [
  "Aatpadi",
  "Islampur",
  "Sangli",
  "Sangli(Phale, Bhajipura Market)",
  "Vita",
 ],
"Sangrur": [
  "Ahmedgarh",
  "Amargarh",
  "Bhawanigarh",
  "Dhuri",
  "Lehra Gaga",
  "Malerkotla",
  "Sangrur",
  "Sunam",
 ],
"Satara": [
  "Karad",
  "Phaltan",
  "Satara",
  "Vai",
 ],
"Satna": [
  "Mehar",
  "Nagod",
  "Satna",
 ],
"Sehore": [
  "Ashta",
  "Baktara",
  "Ichhawar",
  "Jawar",
  "Nasrullaganj",
  "Rehati",
  "Sehore",
  "Shyampur",
 ],
"Seoni": [
  "Chhapara(F&V)",
  "Chhpara",
  "Ghansour",
  "Lakhnadon",
  "Palari",
  "Seoni",
 ],
"Sepahijala": [
  "Bishalgarh",
  "Bishramganj",
  "Boxonagar",
  "Jumpuijala",
  "Melaghar",
  "Sonamura",
 ],
"Shahjahanpur": [
  "Jalalabad",
  "Puwaha",
  "Shahjahanpur",
  "Tilhar",
 ],
"Shajapur": [
  "Agar",
  "Akodiya",
  "Badod",
  "Kalapipal",
  "Kalapipal(F&V)",
  "Nalkehda",
  "Sajapur",
  "Shajapur",
  "Shujalpur",
  "Soyatkalan",
  "Susner",
 ],
"Shamli": [
  "Kairana",
  "Khandhla",
  "Shamli",
  "Thanabhavan",
 ],
"Shehdol": [
  "Beohari",
  "Budhar",
  "Shahdol",
 ],
"Sheikhpura": [
  "Barbigha",
 ],
"Sheohar": [
  "Sheohar",
 ],
"Sheopur": [
  "Sheopurbadod",
  "Sheopurkalan",
 ],
"Shimla": [
  "Mehndli",
  "Rohroo",
  "Shimla",
  "Shimla and Kinnaur(Rampur)",
 ],
"Shimoga": [
  "Sagar",
  "Shimoga",
  "Sorabha",
 ],
"Shivpuri": [
  "Badarwas",
  "Barad",
  "Karera",
  "Khaniadhana",
  "Khanyadhana",
  "Khatora",
  "Kolaras",
  "Pichhour",
  "Pohari",
 ],
"Sholapur": [
  "Akluj",
  "Barshi",
  "Barshi(Vairag)",
  "Dudhani",
  "Karmala",
  "Kurdwadi",
  "Kurdwadi(Modnimb)",
  "Laxmi Sopan Agriculture Produce Marketing Co Ltd",
  "Mangal Wedha",
  "Solapur",
 ],
"Shravasti": [
  "Bhinga",
  "Payagpur",
 ],
"Siddharth Nagar": [
  "Naugarh",
  "Sahiyapur",
 ],
"Sikar": [
  "Fatehpur",
  "Palsana",
  "Surajgarh",
 ],
"Singroli": [
  "Singroli",
 ],
"Sirmore": [
  "Nahan",
  "Paonta Sahib",
 ],
"Sirohi": [
  "Abu Road",
 ],
"Sirsa": [
  "Dabwali",
  "Ellanabad",
  "Rania",
  "Sirsa",
  "kalanwali",
 ],
"Sitapur": [
  "Hargaon (Laharpur)",
  "Mehmoodabad",
  "Sitapur",
  "Viswan",
 ],
"Sivaganga": [
  "Devakottai (Uzhavar Sandhai )",
  "Karaikudi(Uzhavar Sandhai )",
  "Singampunari(Uzhavar Sandhai )",
  "Singampuneri",
  "Sivagangai (Uzhavar Sandhai )",
  "Tirupatthur(Uzhavar Sandhai )",
 ],
"Solan": [
  "Solan",
 ],
"Sonbhadra": [
  "Dudhi",
  "Robertsganj",
 ],
"Sonepur": [
  "Birmaharajpur",
  "Dungurapalli",
  "Pandkital",
 ],
"Sonipat": [
  "Ganaur",
  "Gohana",
  "New Grain Market , Sonipat",
  "Sonepat",
  "Sonepat(Kharkhoda)",
 ],
"Sounth 24 Parganas": [
  "Baruipur(Canning)",
  "Diamond Harbour(South 24-pgs)",
 ],
"South District": [
  "Barpathari",
  "Biokhora",
  "Kalsi",
  "Manubazar",
  "Santir Bazar",
 ],
"South Garo Hills": [
  "Baghmara",
 ],
"South Goa": [
  "Curchorem",
  "Ponda",
 ],
"Srinagar": [
  "Ganderbal",
  "Parimpore",
 ],
"Sukma": [
  "Doranpal",
  "Konta",
  "Kukanar",
 ],
"Sundergarh": [
  "Panposh",
  "Sargipali",
 ],
"Surat": [
  "Mahuva(Anaval)",
  "Mandvi",
  "Nizar",
  "Songadh",
  "Surat",
  "Vyra",
 ],
"Surendranagar": [
  "Chotila",
  "Dasada Patadi",
  "Dhragradhra",
  "Limdi",
  "Vadhvan",
 ],
"Surguja": [
  "Ambikapur",
 ],
"Swai Madhopur": [
  "Gangapur City",
  "Gangapurcity(Old Lal mandi)",
  "Sawai Madhopur",
 ],
"Tarntaran": [
  "Bhikhiwind",
  "Harike",
  "Naushera Pannuan",
  "Patti",
  "Tarantaran",
 ],
"Tenkasi": [
  "Sankarankoil(Uzhavar Sandhai )",
  "Tenkasi(Uzhavar Sandhai )",
 ],
"Thane": [
  "Kalyan",
  "Palghar",
  "Ulhasnagar",
  "Vasai",
 ],
"Thanjavur": [
  "Budalur",
  "Kumbakonam",
  "Kumbakonam (Uzhavar Sandhai )",
  "Papanasam(Uzhavar Sandhai )",
  "Pattukottai",
  "Pattukottai(Uzhavar Sandhai )",
  "Thanjavur",
  "Thanjavur(Uzhavar Sandhai )",
  "Thiruppananthal",
 ],
"The Nilgiris": [
  "Coonoor(Uzhavar Sandhai )",
  "Gudalur(Uzhavar Sandhai )",
  "Udhagamandalam(Uzhavar Sandhai )",
 ],
"Theni": [
  "Andipatti(Uzhavar Sandhai )",
  "Bodinayakanur(Uzhavar Sandhai )",
  "Bodinayakkanur",
  "Chinnamanur",
  "Chinnamanur(Uzhavar Sandhai )",
  "Cumbum",
  "Devaram(Uzhavar Sandhai )",
  "Kambam(Uzhavar Sandhai )",
  "Periyakulam(Uzhavar Sandhai )",
  "Theni",
  "Theni(Uzhavar Sandhai )",
 ],
"Thirssur": [
  "Alengad  VFPCK",
  "Amballur  VFPCK",
  "Chavakkad",
  "Chelakkara",
  "Elanad  VFPCK",
  "Irinjalakkuda",
  "Kodungalloor",
  "Kuzhur  VFPCK",
  "Marottichal  VFPCK",
  "Mattathur VFPCK",
  "Muriyad  VFPCK",
  "Nooluvally  VFPCK",
  "Pariyaram VFPCK",
  "Pazhayannur VFPCK",
  "Puthur  VFPCK",
  "Thrissur",
  "Varandarappilly  VFPCK",
  "Wadakkanchery",
 ],
"Thiruchirappalli": [
  "Lalgudi",
  "Lalgudi(Uzhavar Sandhai )",
  "Manachanallur",
  "Manachanallur(Uzhavar Sandhai )",
  "Manapparai",
  "Manapparai(Uzhavar Sandhai )",
  "Musiri(Uzhavar Sandhai )",
  "Thuraiyur",
 ],
"Thirunelveli": [
  "Ambasamudram",
  "Ambasamudram(Uzhavar Sandhai )",
  "Kandiyaperi(Uzhavar Sandhai )",
  "Melapalayam(Uzhavar Sandhai )",
  "NGO Colony(Uzhavar Sandhai )",
  "Palayamkottai(Uzhavar Sandhai )",
  "Thenkasi",
 ],
"Thirupathur": [
  "Natrampalli(Uzhavar Sandhai )",
  "Vaniyampadi(Uzhavar Sandhai )",
 ],
"Thirupur": [
  "Dharapuram(Uzhavar Sandhai )",
  "Kangayam(Uzhavar Sandhai )",
  "Palladam(Uzhavar Sandhai )",
  "Tiruppur (North) (Uzhavar Sandhai )",
  "Tiruppur (South) (Uzhavar Sandhai )",
 ],
"Thiruvananthapuram": [
  "Anyara(EEC)",
  "Aralamoodu",
  "Attingal",
  "Balaramapuram  VFPCK",
  "Chala",
  "Chenkal  VFPCK",
  "Kattakada",
  "Kattakkada  VFPCK",
  "Kollayil  VFPCK",
  "Kunnathukkal VFPCK",
  "Maranelloor VFPCK",
  "Nedumangadu",
  "Neyyatinkara",
  "Neyyattinkara  VFPCK",
  "Parassala",
  "Pothencode",
  "Vamanapuram",
  "Vengannore  VFPCK",
 ],
"Thiruvannamalai": [
  "Arani",
  "Arani(Uzhavar Sandhai )",
  "Chengam(Uzhavar Sandhai )",
  "Chethupattu",
  "Cheyyar",
  "Cheyyar(Uzhavar Sandhai )",
  "Keelpennathur(Uzhavar Sandhai )",
  "Polur(Thiruvannamalai)",
  "Polur(Uzhavar Sandhai )",
  "Tamarainagar(Uzhavar Sandhai )",
  "Thiruvannamalai",
  "Tiruvannamalai(Uzhavar Sandhai )",
  "Vandavasi",
  "Vettavalam",
 ],
"Thiruvarur": [
  "Mannargudi",
  "Mannargudi I(Uzhavar Sandhai )",
  "Mannargudi II(Uzhavar Sandhai )",
  "Muthupettai(Uzhavar Sandhai )",
  "Needamangalam(Uzhavar Sandhai )",
  "Thiruvarur",
  "Tiruthuraipoondi(Uzhavar Sandhai )",
  "Tiruvarur(Uzhavar Sandhai )",
  "Valangaiman",
 ],
"Thiruvellore": [
  "Ambattur(Uzhavar Sandhai )",
  "Naravarikuppam(Uzhavar Sandhai )",
  "Paruthipattu(Uzhavar Sandhai )",
  "Perambakkam(Uzhavar Sandhai )",
  "Tiruvallur(Uzhavar Sandhai )",
  "Tiruvellore",
 ],
"Thoubal": [
  "Thoubal",
 ],
"Tikamgarh": [
  "Jatara",
  "Khargapur",
  "Niwadi",
  "Prithvipur",
  "Tikamgarh",
 ],
"Tonk": [
  "Deoli",
  "Dooni",
  "Malpura",
  "Malpura(Todaraisingh)",
  "Niwai",
  "Tonk",
  "Uniyara",
 ],
"Tsemenyu": [
  "Tsemenyu",
 ],
"Tuensang": [
  "Tuensang",
 ],
"Tumkur": [
  "Sira",
  "Tiptur",
 ],
"Tuticorin": [
  "Kovilpatti",
  "Kovilpatti(Uzhavar Sandhai )",
  "Thoothukudi",
  "Tuticorin(Uzhavar Sandhai )",
 ],
"Udaipur": [
  "Chhotisadri",
  "Fatehnagar",
  "Udaipur (F&V)",
  "Udaipur (Grain)",
 ],
"UdhamSinghNagar": [
  "Bazpur",
  "Gadarpur",
  "Jaspur(UC)",
  "Kashipur",
  "Khateema",
  "Kicchha",
  "Rudrapur",
  "Sitarganj",
 ],
"Udhampur": [
  "Reasi",
  "Udhampur",
 ],
"Udupi": [
  "Karkala",
  "Kundapura",
  "Udupi",
 ],
"Ujjain": [
  "Badnagar",
  "Khachrod",
  "Mahidpur",
  "Mahidpur(F&V)",
  "Nagda",
  "Tarana",
  "Ujjain",
  "Unhel",
 ],
"Umariya": [
  "Umariya",
 ],
"Una": [
  "Santoshgarh",
  "Una",
 ],
"Unnao": [
  "Bangarmau",
  "Purwa",
  "Unnao",
 ],
"Unokoti": [
  "Masmara",
  "Pabiacherra",
  "Panichowki",
 ],
"Uttar Dinajpur": [
  "Islampur",
  "Kaliaganj",
  "Raiganj",
 ],
"Vadodara(Baroda)": [
  "Padra",
  "Vadodara(Sayajipura)",
 ],
"Valsad": [
  "Chikli(Khorgam)",
  "Pardi(Ugvada)",
  "Pardi(Vapi)",
  "Valsad",
 ],
"Varanasi": [
  "Varanasi",
  "Varanasi(F&V)",
 ],
"Vashim": [
  "Karanja",
  "Malegaon(Vashim)",
  "Mangrulpeer",
  "Manora",
  "Washim",
  "Washim(Ansing)",
 ],
"Vellore": [
  "Ammoor",
  "Arcot",
  "Gudiyatham",
  "Gudiyatham(Uzhavar Sandhai )",
  "Kahithapattarai(Uzhavar Sandhai )",
  "Katpadi (Uzhavar Sandhai )",
  "Katpadi(Uzhavar Santhai)",
  "Thirupathur",
  "Vaniyambadi",
  "Vellore",
 ],
"Vidisha": [
  "Ganjbasoda",
  "Gulabganj",
  "Kurwai",
  "Lateri",
  "Shamshabad",
  "Sironj",
  "Vidisha",
 ],
"Villupuram": [
  "Avalurpet",
  "Gingee",
  "Gingee(Uzhavar Sandhai )",
  "Kallakurichi",
  "Manalurpet",
  "Sangarapuram",
  "Thirukovilur",
  "Thiryagadurgam",
  "Tindivanam",
  "Ulundurpettai",
  "Vikkiravandi",
  "Villupuram",
 ],
"Virudhunagar": [
  "Aruppukottai(Uzhavar Sandhai )",
  "Kariyapatti(Uzhavar Sandhai )",
  "Rajapalayam(Uzhavar Sandhai )",
  "Sathur",
  "Sathur(Uzhavar Sandhai )",
  "Sivakasi(Uzhavar Sandhai )",
  "Srivilliputhur(Uzhavar Sandhai )",
  "Thalavaipuram(Uzhavar Sandhai )",
  "Virudhunagar",
  "Virudhunagar(Uzhavar Sandhai )",
 ],
"Visakhapatnam": [
  "Anakapally",
 ],
"Warangal": [
  "Cherial",
  "Ghanpur",
  "Hanmarkonda(Rythu Bazar)",
  "Jangaon",
  "Kesamudram",
  "Parkal",
  "Warangal",
 ],
"Wardha": [
  "Ashti",
  "Ashti(Karanja)",
  "Hinganghat",
  "Pulgaon",
  "Samudrapur",
  "Sindi",
  "Sindi(Selu)",
  "Wardha",
 ],
"Wayanad": [
  "Kalpetta",
  "Manathavady",
  "Neervaram  VFPCK",
  "Padinjarathara  VFPCK",
  "Pulpally",
  "Sultan bathery",
  "Sulthanbathery  VFPCK",
  "Thondernad  VFPCK",
 ],
"West District": [
  "Champaknagar",
  "Kamalghat",
 ],
"West Garo Hills": [
  "Dadengiri",
  "Tura",
 ],
"West Jaintia Hills": [
  "Jowai",
 ],
"West Khasi Hills": [
  "Nongstoin",
 ],
"Wokha": [
  "Baghty",
  "Wokha Town",
 ],
"Yadgiri": [
  "Shahapur",
  "Yadgir",
 ],
"Yamuna Nagar": [
  "Chhachrauli",
  "Jagadhri",
  "Mustafabad",
  "Radaur",
  "Sadhaura",
  "Yamuna Nagar",
 ],
"Yavatmal": [
  "Babhulgaon",
  "Digras",
  "Kisan Market Yard",
  "Mahesh Krushi Utpanna Bazar, Digras",
  "Ner Parasopant",
  "Pandhakawada",
  "Ramdev Krushi Bazaar",
  "Umarked(Danki)",
  "Vani",
  "Yeotmal",
 ],
"Zunheboto": [
  "Ghathashi",
 ],
"kapurthala": [
  "Bhulath",
  "Bhulath (Nadala)",
  "Kapurthala",
  "Phagwara",
  "Sultanpur",
 ],
 }